import Head from "next/head";
import { Container, css, styled } from "@nextui-org/react";
import App from "../src/App";

export default function Home() {
  return (
    <Container
      css={{
        padding: "0 2rem",
      }}
    >
      {/* Title */}
      <Head>
        <title>Next UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Main Page Content */}
      <Main>
        <App />
      </Main>
      {/* Footer */}
      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <Logo>NextIU</Logo>
        </a>
      </Footer>
    </Container>
  );
}

const Main = styled("main", {
  minHeight: "100vh",
  padding: "4rem 0",
  flex: 1,
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
});

const Footer = styled("footer", {
  display: "flex",
  flex: 1,
  padding: "2rem 0",
  borderTop: "1px solid #E3E3E3",
  justifyContent: "center",
  alignItems: "center",
  a: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#1C1C1C",
    flexGrow: 1,
  },
});

const Logo = styled("span", {
  marginLeft: "0.2rem",
  fontWeight: "$bold",
});
